name: Android Instrument Tests
on:
  pull_request:
    branches: [master, main, uat]
  push:
    branches: [master, main, uat]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.32.0
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -no-snapshot -noaudio -no-boot-anim -gpu swiftshader_indirect
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-test-results
          path: app/build/reports/androidTests/connected/

          
      # - name: Set APK Name
      #   run: |
      #     if [ "${{ github.ref_name }}" == "main" ]; then
      #       echo "APK_NAME=development_standalone_watch_application.apk" >> $GITHUB_ENV
      #     elif [ "${{ github.ref_name }}" == "uat" ]; then
      #       echo "APK_NAME=testing_standalone_watch_application.apk" >> $GITHUB_ENV
      #     elif [ "${{ github.ref_name }}" == "master" ]; then
      #       echo "APK_NAME=release_standalone_watch_application.apk" >> $GITHUB_ENV
      #     shell: /usr/bin/bash -e {0}
      #     env:
      #       JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64
      #       JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64
      #       ANDROID_AVD_HOME: /home/runner/.android/avd


      - name: Development APK
        if: github.ref == 'refs/heads/main'
        run: echo "Development APK build process"
        # Add your specific development build commands here, if any

      - name: Testing APK
        if: github.ref == 'refs/heads/uat'
        run: echo "Testing APK build process"
        # Add your specific testing build commands here, if any

      - name: Release APK
        if: github.ref == 'refs/heads/master'
        run: echo "Release APK build process"
        # Add your specific release build commands here, if any

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-application
          path: app/build/outputs/apk/debug/app-debug.apk
